"use client";

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import { AlertCircle, Check, ImagePlus, Loader2, Palette, Plus, Save, Sparkles, Trash2, X } from "lucide-react";

type Pillar = { name: string; percentage: number };
type Profile = { businessName: string; tagline: string; brief: string; brandPersona: string; niche: string; websiteUrl: string; targetAudience: string; targetAgeMin: number; targetAgeMax: number; targetGender: string; targetLocations: string[]; tone: string; prohibitedClaims: string[]; callsToAction: string[]; colors: string[]; contentPillars: Pillar[] };
type Reference = { id: string; url: string; filename: string };
const empty: Profile = { businessName: "", tagline: "", brief: "", brandPersona: "", niche: "", websiteUrl: "", targetAudience: "", targetAgeMin: 18, targetAgeMax: 45, targetGender: "ALL", targetLocations: [], tone: "Professional & Friendly", prohibitedClaims: [], callsToAction: [], colors: [], contentPillars: [{ name: "Edukasi", percentage: 50 }, { name: "Promosi", percentage: 30 }, { name: "Interaksi", percentage: 20 }] };
const tones = ["Professional & Friendly", "Casual & Professional", "Friendly & Playful", "Authoritative & Expert", "Inspirational & Bold"];
const presets: Record<string, Pillar[]> = { Seimbang: [{ name: "Edukasi", percentage: 40 }, { name: "Promosi", percentage: 30 }, { name: "Interaksi", percentage: 20 }, { name: "Cerita brand", percentage: 10 }], Edukasi: [{ name: "Edukasi", percentage: 60 }, { name: "Promosi", percentage: 20 }, { name: "Interaksi", percentage: 10 }, { name: "Cerita brand", percentage: 10 }], Penjualan: [{ name: "Promosi", percentage: 45 }, { name: "Edukasi", percentage: 30 }, { name: "Testimoni", percentage: 15 }, { name: "Interaksi", percentage: 10 }] };
const addUnique = (values: string[], value: string) => value.trim() && !values.includes(value.trim()) ? [...values, value.trim()] : values;
async function checksum(file: File) { const hash = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); return [...new Uint8Array(hash)].map((n) => n.toString(16).padStart(2, "0")).join(""); }

export default function BrandIdentityPage() {
  const [profile, setProfile] = useState<Profile>(empty); const [initial, setInitial] = useState<Profile>(empty);
  const [references, setReferences] = useState<Reference[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false);
  const [notice, setNotice] = useState<{ error: boolean; text: string } | null>(null); const [tag, setTag] = useState(""); const [color, setColor] = useState("#6D4AFF"); const input = useRef<HTMLInputElement>(null);
  const change = <K extends keyof Profile>(key: K, value: Profile[K]) => setProfile((current) => ({ ...current, [key]: value }));
  const total = profile.contentPillars.reduce((sum, p) => sum + Number(p.percentage || 0), 0); const dirty = JSON.stringify(profile) !== JSON.stringify(initial); const completed = [profile.businessName, profile.brief, profile.targetAudience, profile.brandPersona, profile.colors.length, references.length].filter(Boolean).length;
  async function load() { try { setLoading(true); const [p, r] = await Promise.all([fetch("/api/brand-profile"), fetch("/api/brand-profile/references")]); if (!p.ok) throw new Error("Profil brand tidak dapat dimuat."); const data = await p.json(); const next = data.profile ? { ...empty, ...data.profile, targetLocations: data.profile.targetLocations ?? [], prohibitedClaims: data.profile.prohibitedClaims ?? [], callsToAction: data.profile.callsToAction ?? [], colors: data.profile.colors ?? [], contentPillars: data.profile.contentPillars?.length ? data.profile.contentPillars : empty.contentPillars } : empty; setProfile(next); setInitial(next); if (r.ok) setReferences((await r.json()).references ?? []); } catch (e) { setNotice({ error: true, text: e instanceof Error ? e.message : "Gagal memuat data." }); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; addEventListener("beforeunload", warn); return () => removeEventListener("beforeunload", warn); }, [dirty]);
  async function save(event: FormEvent) { event.preventDefault(); if (total !== 100) return setNotice({ error: true, text: `Total pilar konten harus 100% (saat ini ${total}%).` }); try { setSaving(true); const response = await fetch("/api/brand-profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "Gagal menyimpan."); setProfile(body.profile); setInitial(body.profile); setNotice({ error: false, text: "Brand Identity tersimpan dan langsung menjadi acuan AI." }); } catch (e) { setNotice({ error: true, text: e instanceof Error ? e.message : "Gagal menyimpan." }); } finally { setSaving(false); } }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!file.type.startsWith("image/")) return setNotice({ error: true, text: "Referensi harus berupa gambar." }); if (references.length >= 3) return setNotice({ error: true, text: "Maksimal tiga gambar referensi." }); try { setUploading(true); const reserve = await fetch("/api/assets/upload-url", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ filename: file.name, contentType: file.type, sizeBytes: file.size }) }); const reservation = await reserve.json(); if (!reserve.ok) throw new Error(reservation.message || "Gagal menyiapkan upload."); const put = await fetch(reservation.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!put.ok) throw new Error("Upload gambar gagal."); const done = await fetch("/api/assets/complete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ objectKey: reservation.objectKey, kind: "IMAGE", contentType: file.type, sizeBytes: file.size, checksum: await checksum(file), metadata: { filename: file.name } }) }); const asset = await done.json(); if (!done.ok) throw new Error(asset.message || "Gagal menyimpan asset."); const link = await fetch("/api/brand-profile/references", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assetId: asset.asset.id, filename: file.name }) }); if (!link.ok) throw new Error((await link.json()).message || "Gagal menautkan referensi."); await load(); setNotice({ error: false, text: "Referensi visual ditambahkan." }); } catch (e) { setNotice({ error: true, text: e instanceof Error ? e.message : "Gagal upload." }); } finally { setUploading(false); } }
  async function removeReference(id: string) { if (!confirm("Hapus referensi visual ini?")) return; const response = await fetch(`/api/brand-profile/references?id=${id}`, { method: "DELETE" }); if (response.ok) { setReferences((items) => items.filter((item) => item.id !== id)); setNotice({ error: false, text: "Referensi visual dihapus." }); } else setNotice({ error: true, text: "Referensi tidak dapat dihapus." }); }
  const addTag = (key: "targetLocations" | "callsToAction" | "prohibitedClaims") => { change(key, addUnique(profile[key], tag)); setTag(""); };
  if (loading) return <div className="crm-settings-loading"><Loader2 className="spin" size={24} /> Memuat Brand Identity...</div>;
  return <form onSubmit={save} className="brand-v2"><header className="brand-v2-hero"><div><span><Sparkles size={15} /> Brand Identity 2.0</span><h1>Kenalkan brand Anda ke AI.</h1><p>Routie memakai data ini untuk menyusun ide, caption, dan arahan visual yang konsisten.</p></div><aside><b>{completed}/6</b><small>profil siap</small><i><em style={{ width: `${completed / 6 * 100}%` }} /></i></aside></header>{notice && <div className={`brand-v2-alert ${notice.error ? "error" : "success"}`}><AlertCircle size={18} />{notice.text}</div>}<div className="brand-v2-layout"><main>
    <Section number="01" title="Tentang bisnis" description="Dasar agar AI memahami apa yang Anda tawarkan dan kepada siapa."><div className="brand-v2-grid"><Field label="Nama bisnis *"><input className="crm-input" value={profile.businessName} onChange={(e) => change("businessName", e.target.value)} required /></Field><Field label="Kategori bisnis"><input className="crm-input" value={profile.niche} placeholder="Contoh: F&B, fashion, jasa" onChange={(e) => change("niche", e.target.value)} /></Field><Field label="Tagline"><input className="crm-input" value={profile.tagline} onChange={(e) => change("tagline", e.target.value)} /></Field><Field label="Website (opsional)"><input type="url" className="crm-input" value={profile.websiteUrl} placeholder="https://bisnisanda.com" onChange={(e) => change("websiteUrl", e.target.value)} /></Field></div><Field label="Bisnis Anda membantu apa? *"><textarea className="crm-textarea" rows={4} value={profile.brief} placeholder="Produk, manfaat utama, dan pembeda bisnis Anda." onChange={(e) => change("brief", e.target.value)} required /></Field><Field label="Audiens utama"><textarea className="crm-textarea" rows={2} value={profile.targetAudience} placeholder="Contoh: pemilik UMKM yang ingin..." onChange={(e) => change("targetAudience", e.target.value)} /></Field><div className="brand-v2-grid three"><Field label="Rentang usia"><div className="brand-v2-inline"><input className="crm-input" type="number" min="13" max="100" value={profile.targetAgeMin} onChange={(e) => change("targetAgeMin", +e.target.value)} /><b>s.d.</b><input className="crm-input" type="number" min="13" max="100" value={profile.targetAgeMax} onChange={(e) => change("targetAgeMax", +e.target.value)} /></div></Field><Field label="Gender prioritas"><select className="crm-select" value={profile.targetGender} onChange={(e) => change("targetGender", e.target.value)}><option value="ALL">Semua</option><option value="FEMALE">Perempuan</option><option value="MALE">Laki-laki</option></select></Field><Tags label="Wilayah" values={profile.targetLocations} value={tag} setValue={setTag} add={() => addTag("targetLocations")} remove={(v) => change("targetLocations", profile.targetLocations.filter((x) => x !== v))} /></div></Section>
    <Section number="02" title="Gaya konten" description="Tentukan cara AI menyampaikan pesan dan membagi topik konten."><Field label="Nada komunikasi"><div className="brand-v2-tones">{tones.map((tone) => <button type="button" className={profile.tone === tone ? "selected" : ""} key={tone} onClick={() => change("tone", tone)}>{profile.tone === tone && <Check size={14} />}{tone}</button>)}</div></Field><Field label="Persona AI"><textarea className="crm-textarea" rows={3} value={profile.brandPersona} placeholder="Contoh: hangat, tidak menggurui, gunakan bahasa Indonesia sederhana." onChange={(e) => change("brandPersona", e.target.value)} /></Field><div className="brand-v2-pillar-heading"><div><b>Pilar konten</b><small>Distribusi ide per bulan.</small></div><b className={total === 100 ? "ok" : "bad"}>{total}/100%</b></div><div className="brand-v2-presets">{Object.keys(presets).map((name) => <button type="button" key={name} onClick={() => change("contentPillars", presets[name]!)}>{name}</button>)}</div>{profile.contentPillars.map((pillar, index) => <div className="brand-v2-pillar" key={index}><input className="crm-input" value={pillar.name} onChange={(e) => change("contentPillars", profile.contentPillars.map((x, i) => i === index ? { ...x, name: e.target.value } : x))} /><input type="range" min="0" max="100" step="5" value={pillar.percentage} onChange={(e) => change("contentPillars", profile.contentPillars.map((x, i) => i === index ? { ...x, percentage: +e.target.value } : x))} /><b>{pillar.percentage}%</b><button type="button" onClick={() => profile.contentPillars.length > 1 && change("contentPillars", profile.contentPillars.filter((_, i) => i !== index))}><Trash2 size={16} /></button></div>)}<button type="button" className="brand-v2-add" onClick={() => change("contentPillars", [...profile.contentPillars, { name: "Pilar baru", percentage: 0 }])}><Plus size={15} /> Tambah pilar</button><div className="brand-v2-grid"><Tags label="CTA favorit" values={profile.callsToAction} value={tag} setValue={setTag} add={() => addTag("callsToAction")} remove={(v) => change("callsToAction", profile.callsToAction.filter((x) => x !== v))} /><Tags label="Klaim yang dihindari" values={profile.prohibitedClaims} value={tag} setValue={setTag} add={() => addTag("prohibitedClaims")} remove={(v) => change("prohibitedClaims", profile.prohibitedClaims.filter((x) => x !== v))} /></div></Section>
    <Section number="03" title="Identitas visual" description="Opsional, namun membantu gambar AI terasa lebih konsisten."><Field label="Palet warna"><div className="brand-v2-colors">{profile.colors.map((value) => <span key={value}><i style={{ background: value }} />{value}<button type="button" onClick={() => change("colors", profile.colors.filter((x) => x !== value))}><X size={12} /></button></span>)}<input type="color" value={color} onChange={(e) => setColor(e.target.value)} /><button type="button" onClick={() => change("colors", addUnique(profile.colors, color))}><Plus size={15} /> Tambah</button></div></Field><div className="brand-v2-reference-heading"><div><b>Referensi gaya visual</b><p>Upload poster, feed, atau visual lain yang mewakili gaya brand. Maksimal 3 gambar.</p></div><span>{references.length}/3</span></div><div className="brand-v2-references">{references.map((item) => <article key={item.id}><a href={item.url} target="_blank" rel="noreferrer"><img src={item.url} alt={item.filename} /></a><small>{item.filename}</small><button type="button" onClick={() => removeReference(item.id)}><Trash2 size={15} /></button></article>)}{references.length < 3 && <button type="button" className="brand-v2-dropzone" disabled={uploading} onClick={() => input.current?.click()}>{uploading ? <Loader2 className="spin" /> : <><ImagePlus /><b>Tambahkan referensi</b><small>JPG, PNG, WEBP, AVIF</small></>}</button>}</div><input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={upload} /></Section>
  </main><aside className="brand-v2-preview"><span><Palette size={16} /> Ringkasan AI</span><h2>{profile.businessName || "Nama brand Anda"}</h2><p>{profile.tagline || "Tambahkan tagline untuk memperjelas nilai brand."}</p><dl><div><dt>Gaya bahasa</dt><dd>{profile.tone}</dd></div><div><dt>Audiens</dt><dd>{profile.targetAudience || "Belum diisi"}</dd></div><div><dt>Visual</dt><dd>{profile.colors.length} warna · {references.length} referensi</dd></div></dl><p className="brand-v2-note"><Sparkles size={15} /> Data yang tersimpan dipakai untuk ide, caption, dan gambar AI.</p></aside></div><footer className="brand-v2-savebar"><span>{dirty ? "Ada perubahan yang belum disimpan" : "Semua perubahan tersimpan"}</span><button className="crm-btn crm-btn-primary" disabled={saving}>{saving ? <Loader2 className="spin" size={16} /> : <Save size={16} />}{saving ? "Menyimpan..." : "Simpan Brand Identity"}</button></footer></form>;
}
function Section({ number, title, description, children }: { number: string; title: string; description: string; children: React.ReactNode }) { return <section className="brand-v2-card"><header><span>{number}</span><div><h2>{title}</h2><p>{description}</p></div></header>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="brand-v2-field"><b>{label}</b>{children}</label>; }
function Tags({ label, values, value, setValue, add, remove }: { label: string; values: string[]; value: string; setValue(value: string): void; add(): void; remove(value: string): void }) { return <Field label={label}><div className="brand-v2-tags">{values.map((item) => <span key={item}>{item}<button type="button" onClick={() => remove(item)}><X size={12} /></button></span>)}</div><div className="brand-v2-tag-input"><input className="crm-input" value={value} onChange={(e) => setValue(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); add(); } }} /><button type="button" onClick={add}><Plus size={15} /></button></div></Field>; }
